### ISSUE TITLE
Please cite the previous close works for respect.

### ISSUE THREAD

**Issue by lxtGH** [HanchenTai/OV-SAM3D#3]
Our work Open-Vocabulary SAM was released on 1/18/2024. 

https://github.com/HarborYuan/ovsam.

However, I look the entire paper and I do not find any mention of this, even the name is nearly the same.

In addition, other several close works are missing.

Semantic-sam: Segment and recognize anything at any granularity.

Sam-clip: Merging vision foundation models towards semantic and spatial understanding.

**Comment by HanchenTai** [comment]
Sorry for the late reply. We greatly admire your work Open-Vocabulary SAM and try to get some inspiration from it, but in the process of practice, we found that Open-Vocabulary SAM blends SAM and clip well, which makes it difficult to better integrate into the other modules in our OV-SAM3D. Therefore, we ended up just keeping the original SAM and did not utilize related variants of SAM. Your suggestion is very meaningful, and we will appropriately cite these related works in 2D field in the next version!
